libpetros: fdeclarations works for a file list

diff --git a/tool/fdeclarations b/tool/fdeclarations
--- a/tool/fdeclarations
+++ b/tool/fdeclarations
@@ -1,22 +1,17 @@
-#!/usr/bin/env python3
-# fdeclarations.py: Tool to separate subroutine arguments from
-#                   declarations of local variables
-#
-# Copyright (C) 2012    Elias Rabel
-#
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, either version 3 of the License, or
-# (at your option) any later version.
-#
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-#
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+#!/bin/sh
 
+me=tool/fdeclarations
+: ${PYTHON=python}
+
+err ()
+{
+    printf >&2 %s\\n "$me: $*"
+    exit 2
+}
+
+for i
+do
+"$PYTHON" -c '
 """
 Tool to separate subroutine arguments from declarations of local variables.
 
@@ -352,4 +347,24 @@ if __name__ == "__main__":
     f.close()
 
     printWrapperCode(subname, args, varlist)
+' "$i"
+if ! test $? = 0; then err "fail for '$i'"; fi
+done
 
+# fdeclarations.py: Tool to separate subroutine arguments from
+#                   declarations of local variables
+#
+# Copyright (C) 2012    Elias Rabel
+#
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
